language: r
sudo: required
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

git:
  depth: 3

env:
  global:
    - secure: GITHUB_PAT

r_packages:
 - devtools
 - dplyr
 - ggplot2
 - futile.logger

install:
  - R -e "0" --args --bootstrap-packrat

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh